apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u88vljhoq-go 
  janus-idp.io/tekton: u88vljhoq-go
  backstage.io/kubernetes-id: u88vljhoq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u88vljhoq-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  